// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfmuTasLN0sVpbat1YUdZzsJqiQL1r9DA',
    appId: '1:684266865426:web:5dad93b9691626dc69a9cb',
    messagingSenderId: '684266865426',
    projectId: 'livenotes-8d75a',
    authDomain: 'livenotes-8d75a.firebaseapp.com',
    storageBucket: 'livenotes-8d75a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8MGXQsUSdd-X5-JNiP09FXV-zna0-Zww',
    appId: '1:684266865426:android:b541aa50d20b390569a9cb',
    messagingSenderId: '684266865426',
    projectId: 'livenotes-8d75a',
    storageBucket: 'livenotes-8d75a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPgOmSZQBC28mHriIp9O-RvdFLFJx5rfM',
    appId: '1:684266865426:ios:77d0296cc8f7dc3069a9cb',
    messagingSenderId: '684266865426',
    projectId: 'livenotes-8d75a',
    storageBucket: 'livenotes-8d75a.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPgOmSZQBC28mHriIp9O-RvdFLFJx5rfM',
    appId: '1:684266865426:ios:77d0296cc8f7dc3069a9cb',
    messagingSenderId: '684266865426',
    projectId: 'livenotes-8d75a',
    storageBucket: 'livenotes-8d75a.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfmuTasLN0sVpbat1YUdZzsJqiQL1r9DA',
    appId: '1:684266865426:web:0d50def4b9353cfe69a9cb',
    messagingSenderId: '684266865426',
    projectId: 'livenotes-8d75a',
    authDomain: 'livenotes-8d75a.firebaseapp.com',
    storageBucket: 'livenotes-8d75a.firebasestorage.app',
  );
}
